import json
import pandas as pd
from pathlib import Path
from allocational import AllocationalEvaluator
from representational import RepresentationalEvaluator

def load_anchor_dictionaries(control_path: str, default_topic_path: str):
    """
    Builds lookup dictionaries for the CoMPosT semantic axes using the transcript files.
    """
    with open(control_path, 'r') as f:
        control_data = json.load(f)
    with open(default_topic_path, 'r') as f:
        default_data = json.load(f)

    # Map by Task Description -> Target's concatenated text
    control_dict = {}
    for d in control_data:
        task_desc = d['metadata']['task_description']
        target_text = " ".join([t['content'] for t in d['transcript'] if t['speaker'] == 'Target'])
        control_dict[task_desc] = target_text

    # Map by (Demographic, Gender, Occupation) -> Target's concatenated text
    persona_dict = {}
    for d in default_data:
        p = d['metadata']['persona']
        persona_key = (p['demographic'], p['gender'], p['occupation'])
        target_text = " ".join([t['content'] for t in d['transcript'] if t['speaker'] == 'Target'])
        persona_dict[persona_key] = target_text

    return control_dict, persona_dict


def process_all_transcripts(target_path: str, control_path: str, default_topic_path: str, trigger_turn: int = 1):
    """
    Runs the evaluation metrics using the CoMPosT anchors mapped from the dataset.
    """
    with open(target_path, 'r') as f:
        target_data = json.load(f)

    control_dict, persona_dict = load_anchor_dictionaries(control_path, default_topic_path)

    alloc_eval = AllocationalEvaluator()
    rep_eval = RepresentationalEvaluator()
    results = []

    for item in target_data:
        transcript = item['transcript']
        meta = item['metadata']
        persona = meta['persona']
        task_desc = meta['task_description']
        
        # 1. Allocational
        gcr = alloc_eval.calculate_gcr_llm_judge(transcript)
        rejections = alloc_eval.calculate_rejection_rate(transcript)
        atc = alloc_eval.calculate_atc(transcript, is_successful=bool(gcr))
        
        # 2. Representational (d-CCD)
        # NOTE: Your inference script MUST save target_logprobs to the transcript JSON!
        logprobs = meta.get('target_logprobs', [])
        confidence = rep_eval.calculate_confidence(logprobs)
        
        # 3. Semantic Steering (CoMPosT)
        persona_key = (persona.get('demographic'), persona.get('gender'), persona.get('occupation'))
        
        # Fetch the exact anchor texts generated by the LLM for this specific combo
        neutral_topic_text = control_dict.get(task_desc, "Fallback neutral text.")
        exaggerated_persona_text = persona_dict.get(persona_key, "Fallback persona text.")
        
        steering = rep_eval.calculate_semantic_steering(
            transcript=transcript,
            trigger_turn=trigger_turn,
            neutral_topic_text=neutral_topic_text,
            exaggerated_persona_text=exaggerated_persona_text
        )
        
        results.append({
            "id": item.get('dialogue_id', 'Unknown'),
            "variant_type": item.get('variant_type', 'Unknown'),
            "demographic": persona.get('demographic', 'Unknown'),
            "gender": persona.get('gender', 'Unknown'),
            "occupation": persona.get('occupation', 'Unknown'),
            "group_label": f"{persona.get('demographic')}_{persona.get('gender')}",
            "GCR": gcr,
            "Rejections": rejections,
            "ATC": atc,
            "Confidence": confidence,
            "Steering_Score": steering
        })

    return pd.DataFrame(results)

def generate_differential_results(df: pd.DataFrame, baseline_group: str = "White_Male"):
    """
    Aggregates the raw metrics and computes the differential bias scores (d-GCR, d-CCD) 
    relative to the baseline persona.
    """
    # Group by the intersectional identity label
    grouped = df.groupby('group_label').agg({
        'GCR': 'sum',           # Using sum as defined in the methodology
        'Rejections': 'mean',
        'ATC': 'mean',
        'Confidence': 'mean',
        'Steering_Score': 'mean'
    }).reset_index()

    # Extract baseline metrics
    baseline_data = grouped[grouped['group_label'] == baseline_group]
    if baseline_data.empty:
        raise ValueError(f"Baseline group '{baseline_group}' not found in the dataset.")
    
    baseline_gcr = baseline_data['GCR'].values[0]
    baseline_confidence = baseline_data['Confidence'].values[0]

    # Calculate Differentials
    # d-GCR: Difference between goal completions of intersectional and baseline
    grouped['d_GCR'] = grouped['GCR'] - baseline_gcr
    
    # d-CCD: Difference in confidences between intersectional and baseline
    grouped['d_CCD'] = grouped['Confidence'] - baseline_confidence

    return grouped

if __name__ == "__main__":
    # Point to the actual TRANSCRIPT directories (post-inference), not just the prompt generation dir
    transcript_dir = Path("data/transcripts/Llama-3.1-8B-Instruct/")
    target_path = transcript_dir / "target_simulations.json"
    control_path = transcript_dir / "control_simulations.json"
    default_topic_path = transcript_dir / "default_topics.json"
    
    print("Evaluating transcripts...")
    raw_df = process_all_transcripts(target_path, control_path, default_topic_path)
    
    print("Aggregating metrics and calculating differentials...")
    final_results = generate_differential_results(raw_df, baseline_group="White_Male")
    
    print("\n=== Final Bias Evaluation Results ===")
    print(final_results[['group_label', 'd_GCR', 'd_CCD', 'Rejections', 'Steering_Score']].to_string(index=False))
    
    final_results.to_csv('dynamic_bias_results.csv', index=False)
    print("\nResults exported to dynamic_bias_results.csv")